; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
; This section contains general settings that can be used to change how Rainmeter behaves.
Update=1000

[Metadata]
; Contains basic information of the skin.
Name=LHMMonitor FAN
Author=TwilightApteryx
Information=Display FAN Information.
License=
Version=1.0.0

[Variables]
; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
FontFace=Consolas
RootX=10
Sub1X=15

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

[MeterBackground]
Meter=Shape
Shape=Rectangle 0,0,200,190 | Fill Color 0,0,0,220 | StrokeWidth 0
DynamicVariables=1

[MeterStyleTitle]
FontFace=#FontFace#
FontColor=255,200,0
FontSize=10
FontWeight=700
AntiAlias=1

[MeterStyleData]
FontFace=#FontFace#
FontColor=255,255,255
FontSize=8
AntiAlias=1

[MeterStyleDataSub1]
FontColor=220,220,220

[MeterStyleBar]
BarColor=0,200,0
SolidColor=0,200,0,150
BarOrientation=Horizontal

[MeterStyleBaseLabelPos]
X=10
Y=40
W=180
H=14

[MeterStyleBaseValuePos]
X=190
Y=0r
W=180
H=14

[MeterStyleBaseBarPos]
X=12
Y=12r
W=177
H=2

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[MeasureFan1]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Fan
SensorName=Fan #1
MaxValue=3000
[MeasureFan2]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Fan
SensorName=Fan #2
MaxValue=3000
[MeasureFan3]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Fan
SensorName=Fan #3
MaxValue=3000
[MeasureFan4]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Fan
SensorName=Fan #4
MaxValue=3000
[MeasureFan5]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Fan
SensorName=Fan #5
MaxValue=3000
[MeasureFan6]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Fan
SensorName=Fan #6
MaxValue=3000
[MeasureFan7]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Fan
SensorName=Fan #7
MaxValue=3000

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

[MeterTitle]
Meter=String
MeterStyle=MeterStyleTitle
X=10
Y=10
Text=Nuvoton NCT6799D

; FAN 1
[MeterLabelFAN1]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
X=15
Y=40
Text=FAN #1

[MeterValueFAN1]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureFAN1
StringAlign=Right
Text=%1 RPM

[MeterBarFAN#1]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureFAN1

; FAN 2
[MeterLabelFAN2]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
X=15
Y=60
Text=FAN #2

[MeterValueFAN2]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureFAN2
StringAlign=Right
Text=%1 RPM

[MeterBarFAN#2]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureFAN2

; FAN 3
[MeterLabelFAN3]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
X=15
Y=80
Text=FAN #3

[MeterValueFAN3]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureFAN3
StringAlign=Right
Text=%1 RPM

[MeterBarFAN#3]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureFAN3

; FAN 4
[MeterLabelFAN4]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
X=15
Y=100
Text=FAN #4

[MeterValueFAN4]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureFAN4
StringAlign=Right
Text=%1 RPM

[MeterBarFAN#4]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureFAN4

; FAN 5
[MeterLabelFAN5]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
X=15
Y=120
Text=FAN #5

[MeterValueFAN5]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureFAN5
StringAlign=Right
Text=%1 RPM

[MeterBarFAN#5]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureFAN5

; FAN 6
[MeterLabelFAN6]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
X=15
Y=140
Text=FAN #6

[MeterValueFAN6]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureFAN6
StringAlign=Right
Text=%1 RPM

[MeterBarFAN#6]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureFAN6

; FAN 7
[MeterLabelFAN7]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
X=15
Y=160
Text=FAN #7

[MeterValueFAN7]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureFAN7
StringAlign=Right
Text=%1 RPM

[MeterBarFAN#7]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureFAN7
