; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
; This section contains general settings that can be used to change how Rainmeter behaves.
Update=1000

[Metadata]
; Contains basic information of the skin.
Name=LHMMonitor CPU
Author=TwilightApteryx
Information=Display CPU Information.
License=
Version=1.0.0

[Variables]
; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
FontFace=Consolas
RootX=10
Sub1X=15
BarColorTempSafe=0,200,0
BarColorTempWarn=200,200,0
BarColorTempDang=200,0,0
SafeTemp=75
WarnTemp=85

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

[MeterBackground]
Meter=Shape
Shape=Rectangle 0,0,200,110 | Fill Color 0,0,0,220 | StrokeWidth 0
DynamicVariables=1

[MeterStyleTitle]
FontFace=#FontFace#
FontColor=255,200,0
FontSize=10
FontWeight=700
AntiAlias=1

[MeterStyleData]
FontFace=#FontFace#
FontColor=255,255,255
FontSize=8
AntiAlias=1

[MeterStyleDataSub1]
FontColor=220,220,220

[MeterStyleBar]
BarColor=#BarColorTempSafe#
SolidColor=0,200,0,150
BarOrientation=Horizontal

[MeterStyleBaseLabelPos]
X=10
Y=40
W=180
H=14

[MeterStyleBaseValuePos]
X=190
Y=0r
W=180
H=14

[MeterStyleBaseBarPos]
X=12
Y=12r
W=177
H=2

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[MeasureGPULoad]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=AMD Radeon RX 9070 XT
SensorType=Load
SensorName=GPU Core

[MeasureGPUTemp]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=AMD Radeon RX 9070 XT
SensorType=Temperature
SensorName=GPU Core

[MeasureGPUMemTotal]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=AMD Radeon RX 9070 XT
SensorType=SmallData
SensorName=GPU Memory Total

[MeasureGPUMemUsed]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=AMD Radeon RX 9070 XT
SensorType=SmallData
SensorName=GPU Memory Used
MaxValue=[MeasureGPUMemTotal:]
DynamicVariables=1

[MeasureGPUMemUsedRatio]
Measure=Calc
Formula=[MeasureGPUMemUsed] / [MeasureGPUMemTotal]
DynamicVariables=1

[MeasureGPUTempBarColorChanger]
Measure=Calc
Formula=(MeasureGPUTemp < #SafeTemp# ? -1 : (MeasureGPUTemp < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarGPUTemp BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarGPUTemp BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarGPUTemp BarColor #BarColorTempDang#

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

[MeterTitle]
Meter=String
MeterStyle=MeterStyleTitle
X=10
Y=10
Text=AMD Radeon RX 9070 XT

; GPU Load
[MeterLabelGPULoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
Y=40
Text=GPU Load

[MeterValueGPULoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureGPULoad
StringAlign=Right
Text=%1%

[MeterBarGPULoad]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureGPULoad

; GPU Temp
[MeterLabelGPUTemp]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
Y=60
Text=GPU Temp

[MeterValueGPUTemp]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureGPUTemp
StringAlign=Right
Text=%1C
NumOfDecimals=2

[MeterBarGPUTemp]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureGPUTemp

; GPU Mem
[MeterLabelGPUMem]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
Y=80
Text=GPU Mem

[MeterValueGPUMem]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureGPUMemUsedRatio
StringAlign=Right
Text=%1%
NumOfDecimals=1
Percentual=1

[MeterBarGPUMem]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureGPUMemUsedRatio
