; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
; This section contains general settings that can be used to change how Rainmeter behaves.
Update=1000

[Metadata]
; Contains basic information of the skin.
Name=LHMMonitor CPU
Author=TwilightApteryx
Information=Display CPU Information.
License=
Version=1.0.0

[Variables]
; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
FontFace=Consolas
RootX=10
Sub1X=15
BarColorTempSafe=0,200,0
BarColorTempWarn=200,200,0
BarColorTempDang=200,0,0
SafeTemp=75
WarnTemp=85

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

[MeterBackground]
Meter=Shape
Shape=Rectangle 0,0,200,210 | Fill Color 0,0,0,220 | StrokeWidth 0
DynamicVariables=1

[MeterStyleTitle]
FontFace=#FontFace#
FontColor=255,200,0
FontSize=10
FontWeight=700
AntiAlias=1

[MeterStyleData]
FontFace=#FontFace#
FontColor=255,255,255
FontSize=8
AntiAlias=1

[MeterStyleDataSub1]
FontColor=220,220,220

[MeterStyleBar]
BarColor=#BarColorTempSafe#
SolidColor=0,200,0,150
BarOrientation=Horizontal

[MeterStyleBaseLabelPos]
X=10
Y=40
W=180
H=14

[MeterStyleBaseValuePos]
X=190
Y=0r
W=180
H=14

[MeterStyleBaseBarPos]
X=12
Y=12r
W=177
H=2

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[MeasureCPULoad]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=AMD Ryzen 5 9600X
SensorType=Load
SensorName=CPU Total

[MeasureCPUCoreTemp]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=AMD Ryzen 5 9600X
SensorType=Temperature
SensorName=Core (Tctl/Tdie)

[MeasureCPUCoreTemp1]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Temperature
SensorName=Temperature #1
[MeasureCPUCoreTemp2]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Temperature
SensorName=Temperature #2
[MeasureCPUCoreTemp3]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Temperature
SensorName=Temperature #3
[MeasureCPUCoreTemp4]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Temperature
SensorName=Temperature #4
[MeasureCPUCoreTemp5]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Temperature
SensorName=Temperature #5
[MeasureCPUCoreTemp6]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Nuvoton NCT6799D
SensorType=Temperature
SensorName=Temperature #6

[MeasureCPUCoreTempBarColorChanger]
Measure=Calc
Formula=(MeasureCPUCoreTemp < #SafeTemp# ? -1 : (MeasureCPUCoreTemp < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarCPUCoreTemp BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarCPUCoreTemp BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarCPUCoreTemp BarColor #BarColorTempDang#
[MeasureCPUCoreTemp1BarColorChanger]
Measure=Calc
Formula=(MeasureCPUCoreTemp1 < #SafeTemp# ? -1 : (MeasureCPUCoreTemp1 < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarCPUCoreTemp1 BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarCPUCoreTemp1 BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarCPUCoreTemp1 BarColor #BarColorTempDang#
[MeasureCPUCoreTemp2BarColorChanger]
Measure=Calc
Formula=(MeasureCPUCoreTemp2 < #SafeTemp# ? -1 : (MeasureCPUCoreTemp2 < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarCPUCoreTemp2 BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarCPUCoreTemp2 BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarCPUCoreTemp2 BarColor #BarColorTempDang#
[MeasureCPUCoreTemp3BarColorChanger]
Measure=Calc
Formula=(MeasureCPUCoreTemp3 < #SafeTemp# ? -1 : (MeasureCPUCoreTemp3 < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarCPUCoreTemp3 BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarCPUCoreTemp3 BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarCPUCoreTemp3 BarColor #BarColorTempDang#
[MeasureCPUCoreTemp4BarColorChanger]
Measure=Calc
Formula=(MeasureCPUCoreTemp4 < #SafeTemp# ? -1 : (MeasureCPUCoreTemp4 < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarCPUCoreTemp4 BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarCPUCoreTemp4 BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarCPUCoreTemp4 BarColor #BarColorTempDang#
[MeasureCPUCoreTemp5BarColorChanger]
Measure=Calc
Formula=(MeasureCPUCoreTemp5 < #SafeTemp# ? -1 : (MeasureCPUCoreTemp5 < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarCPUCoreTemp5 BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarCPUCoreTemp5 BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarCPUCoreTemp5 BarColor #BarColorTempDang#
[MeasureCPUCoreTemp6BarColorChanger]
Measure=Calc
Formula=(MeasureCPUCoreTemp6 < #SafeTemp# ? -1 : (MeasureCPUCoreTemp6 < #WarnTemp# ? 1 : 2))  
IfBelowValue=0
IfBelowAction=!SetOption MeterBarCPUCoreTemp6 BarColor #BarColorTempSafe#
ifEqualValue=1
IfEqualAction=!SetOption MeterBarCPUCoreTemp6 BarColor #BarColorTempWarn#
IfAboveValue=1
IfAboveAction=!SetOption MeterBarCPUCoreTemp6 BarColor #BarColorTempDang#

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

[MeterTitle]
Meter=String
MeterStyle=MeterStyleTitle
X=10
Y=10
Text=AMD Ryzen 5 9600X

; CPU Load
[MeterLabelCPULoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
Y=40
Text=CPU Load

[MeterValueCPULoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureCPULoad
StringAlign=Right
Text=%1%
NumOfDecimals=2

[MeterBarCPULoad]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPULoad

; CPU Core Temp
[MeterLabelCPUCoreTemp]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
Y=60
Text=CPU Core Temp

[MeterValueCPUCoreTemp]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureCPUCoreTemp
StringAlign=Right
Text=%1C
NumOfDecimals=1

[MeterBarCPUCoreTemp]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPUCoreTemp
BarColor=[MeasureCPUCoreTempBarColorChanger]

; CPU Par Core Temp 1
[MeterLabelCPUCoreTemp1]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseLabelPos
X=15
Y=80
Text=CPU Core Temp #1

[MeterValueCPUCoreTemp1]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseValuePos
MeasureName=MeasureCPUCoreTemp1
StringAlign=Right
Text=%1C
NumOfDecimals=1

[MeterBarCPUCoreTemp1]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPUCoreTemp1
BarColor=[MeasureCPUCoreTemp1BarColorChanger]

; CPU Par Core Temp 2
[MeterLabelCPUCoreTemp2]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseLabelPos
X=15
Y=100
Text=CPU Core Temp #2

[MeterValueCPUCoreTemp2]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseValuePos
MeasureName=MeasureCPUCoreTemp2
StringAlign=Right
Text=%1C
NumOfDecimals=1

[MeterBarCPUCoreTemp2]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPUCoreTemp2
BarColor=[MeasureCPUCoreTemp2BarColorChanger]

; CPU Par Core Temp 3
[MeterLabelCPUCoreTemp3]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseLabelPos
X=15
Y=120
Text=CPU Core Temp #3

[MeterValueCPUCoreTemp3]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseValuePos
MeasureName=MeasureCPUCoreTemp3
StringAlign=Right
Text=%1C
NumOfDecimals=1

[MeterBarCPUCoreTemp3]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPUCoreTemp3
BarColor=[MeasureCPUCoreTemp3BarColorChanger]

; CPU Par Core Temp 4
[MeterLabelCPUCoreTemp4]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseLabelPos
X=15
Y=140
Text=CPU Core Temp #4

[MeterValueCPUCoreTemp4]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseValuePos
MeasureName=MeasureCPUCoreTemp4
StringAlign=Right
Text=%1C
NumOfDecimals=1

[MeterBarCPUCoreTemp4]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPUCoreTemp4

; CPU Par Core Temp 5
[MeterLabelCPUCoreTemp5]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseLabelPos
X=15
Y=160
Text=CPU Core Temp #5

[MeterValueCPUCoreTemp5]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseValuePos
MeasureName=MeasureCPUCoreTemp5
StringAlign=Right
Text=%1C
NumOfDecimals=1

[MeterBarCPUCoreTemp5]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPUCoreTemp5

; CPU Par Core Temp 6
[MeterLabelCPUCoreTemp6]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseLabelPos
X=15
Y=180
Text=CPU Core Temp #6

[MeterValueCPUCoreTemp6]
Meter=String
MeterStyle=MeterStyleData | MeterStyleDataSub1 | MeterStyleBaseValuePos
MeasureName=MeasureCPUCoreTemp6
StringAlign=Right
Text=%1C
NumOfDecimals=1

[MeterBarCPUCoreTemp6]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureCPUCoreTemp6
