; Lines starting ; (semicolons) are commented out.
; That is, they do not affect the code and are here for demonstration purposes only.
; ----------------------------------

[Rainmeter]
; This section contains general settings that can be used to change how Rainmeter behaves.
Update=1000

[Metadata]
; Contains basic information of the skin.
Name=LHMMonitor Memory
Author=TwilightApteryx
Information=Display Memory Information.
License=
Version=1.0.0

[Variables]
; Variables declared here can be used later on between two # characters (e.g. #MyVariable#).
FontFace=Consolas
RootX=10
Sub1X=15

; ----------------------------------
; STYLES are used to "centralize" options
; ----------------------------------

[MeterBackground]
Meter=Shape
Shape=Rectangle 0,0,200,90 | Fill Color 0,0,0,220 | StrokeWidth 0
DynamicVariables=1

[MeterStyleTitle]
FontFace=#FontFace#
FontColor=255,200,0
FontSize=10
FontWeight=700
AntiAlias=1

[MeterStyleData]
FontFace=#FontFace#
FontColor=255,255,255
FontSize=8
AntiAlias=1

[MeterStyleDataSub1]
FontColor=220,220,220

[MeterStyleBar]
BarColor=0,200,0
SolidColor=0,200,0,150
BarOrientation=Horizontal

[MeterStyleBaseLabelPos]
X=10
Y=40
W=180
H=14

[MeterStyleBaseValuePos]
X=190
Y=0r
W=180
H=14

[MeterStyleBaseBarPos]
X=12
Y=12r
W=177
H=2

; ----------------------------------
; MEASURES return some kind of value
; ----------------------------------

[MeasureMemLoad]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Total Memory
SensorType=Load
SensorName=Memory

[MeasureVirMemLoad]
Measure=Plugin
Plugin=LHMMonitor.dll
HardwareName=Virtual Memory
SensorType=Load
SensorName=Memory

; ----------------------------------
; METERS display images, text, bars, etc.
; ----------------------------------

[MeterTitle]
Meter=String
MeterStyle=MeterStyleTitle
X=10
Y=10
Text=CMK32GX5M2E6000Z36

; Memory Load
[MeterMemLoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
Y=40
Text=Memory Load

[MeterValueMemLoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureMemLoad
StringAlign=Right
Text=%1%
NumOfDecimals=2

[MeterBarMemLoad]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureMemLoad

; Virtual Memory Load
[MeterLabelVirMemLoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseLabelPos
Y=60
Text=Virtual Memory Load

[MeterValueVirMemLoad]
Meter=String
MeterStyle=MeterStyleData | MeterStyleBaseValuePos
MeasureName=MeasureVirMemLoad
StringAlign=Right
Text=%1%
NumOfDecimals=2

[MeterBarVirMemLoad]
Meter=Bar
MeterStyle=MeterStyleBar | MeterStyleBaseBarPos
MeasureName=MeasureVirMemLoad
